name = "discord-app"
type = "webpack"
zone_id = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2024-04-15"
route = "/"
usage_model = "bundled"
main = "server.js"
node_compat = true
